package cn.projects.team.demo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.projects.team.demo.model.Contact;
import cn.projects.team.demo.model.ContactGroup;

import cn.projects.team.demo.greendao.ContactDao;
import cn.projects.team.demo.greendao.ContactGroupDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactDaoConfig;
    private final DaoConfig contactGroupDaoConfig;

    private final ContactDao contactDao;
    private final ContactGroupDao contactGroupDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        contactGroupDaoConfig = daoConfigMap.get(ContactGroupDao.class).clone();
        contactGroupDaoConfig.initIdentityScope(type);

        contactDao = new ContactDao(contactDaoConfig, this);
        contactGroupDao = new ContactGroupDao(contactGroupDaoConfig, this);

        registerDao(Contact.class, contactDao);
        registerDao(ContactGroup.class, contactGroupDao);
    }
    
    public void clear() {
        contactDaoConfig.clearIdentityScope();
        contactGroupDaoConfig.clearIdentityScope();
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public ContactGroupDao getContactGroupDao() {
        return contactGroupDao;
    }

}
